CONVERSATION_PROMPT = (
    "Summarize one business chat (a WhatsApp group or direct chat) for an operations user "
    "at a B2B supplier.\n"
    "Set topics to the business topics, decisions, and key points discussed in the chat. "
    "Business means orders, quantities, prices, quotations, deliveries, schedules, specifications, drawings, "
    "revisions, approvals, payments, invoices, complaints, and commitments or follow-ups between the parties. "
    "Ignore greetings, small talk, jokes, and anything unrelated to the business.\n"
    "For each topic set title to a short heading of 3 to 10 words that names the subject, "
    "for example the order, item, or issue. "
    "Set kind to decision when something was agreed, approved, or confirmed; "
    "to key_point for an important fact, number, or commitment; otherwise to topic.\n"
    "Set summary to one EvidenceValue of 1 to 4 complete sentences that state what was discussed, "
    "who asked or agreed, the specific quantities, dates, and prices mentioned, the outcome, "
    "and any open follow-up. Write prose, not a list of messages, and do not quote messages verbatim. "
    "Cite every evidence chunk needed to support the summary.\n"
    "Set date to the date of the latest message about the topic as YYYY-MM-DD, or null if it is not stated.\n"
    "Merge messages about the same subject into one topic, and keep a later change together with the original "
    "request so the current state is clear. Order topics with the most recent first. "
    "Return an empty list when the chat contains nothing business-related."
)
